
train:
  dataset: 'cifar10'
  model: 'resnet18'
  dataset_path: '/home/cyf/Autosparse/experiment_0416before/dataset_results/cifar10_resnet18_snip/batch64_lr0.01_num_pepoch20_seed0_0/dataset/data.pkl'
  method: 'snip'
  epochs: 10
  train_batchsize: 4096
  test_batchsize: 4096
  lr: 0.01
  prediction_model: 'resnet18'
  save_name: 
  # data: None

prune:
  pruner: 'snip'
  prune_epochs: 0
  
policy:
  expid: 'cifar10_res18_20it_percent_mag_important'
  gpu: 0
  run_choice: prune_iterative #prune_iterative, prune_once, prune_prediction
  seed: 1
