
train:
  model: 'resnet18'
  dataset_path: 'autos_dataset/cifar10/mag/cifar10_res18_40it_mag_important-2024-01-22-13-37/data.pkl'
  method: 'mag'
  epoch: 10
  save_name: 'cifar10_res18_20it_not_percent_mag_important-2024-03-15-16-23'
  # data: None

prune:

policy:
  expid: 'cifar10_res18_20it_percent_mag_important'
  prediction_model: 'resnet18'
  gpu: 0
  batch_size: 1024
  lr: 0.001
  epochs: 20
