
train:
  dataset: 'cifar10'
  model: 'resnet18'
  dataset_path: 'autos_dataset/cifar10/mag/cifar10_res18_40it_mag_important-2024-01-22-13-37/data.pkl'
  method: 'mag'
  epochs: 10
  train_batchsize: 4096
  test_batchsize: 4096
  lr: 0.001
  prediction_model: 'resnet18'
  save_name: 'cifar10_res18_20it_not_percent_mag_important-2024-03-15-16-23'
  # data: None

prune:
  pruner: 'mag'

policy:
  expid: 'cifar10_res18_20it_percent_mag_important'
  gpu: 0
  run_choice: prune_iterative #prune_iterative, prune_once, prune_autos
